# Generated by Django 3.2.4 on 2021-09-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_prescription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user_med',
        ),
    ]
