# Generated by Django 3.2.4 on 2021-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_prescription_user_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
